version: "2"
services:
   namenode:
      image: apache/hadoop:latest
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode1:
      image: apache/hadoop:latest
      hostname: datanode1
      command: ["hdfs", "datanode"]
      env_file:
        - ./config     
   datanode2:
      image: apache/hadoop:latest
      hostname: datanode2
      command: ["hdfs", "datanode"]
      env_file:
        - ./config  
   datanode3:
      image: apache/hadoop:latest
      hostname: datanode3
      command: ["hdfs", "datanode"]
      env_file:
        - ./config   
   resourcemanager:
      image: apache/hadoop:latest
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
   nodemanager1:
      image: apache/hadoop:latest
      hostname: nodemanager1
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
   nodemanager2:
      image: apache/hadoop:latest
      hostname: nodemanager2
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
   nodemanager3:
      image: apache/hadoop:latest
      hostname: nodemanager3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
